require("eecs.plugins-setup")
require("eecs.core.options")
require("eecs.core.keymaps")
require("eecs.core.colorscheme")
require("eecs.plugins.comment")
require("eecs.plugins.nvim-tree")
require("eecs.plugins.lualine")
require("eecs.plugins.telescope")
require("eecs.plugins.nvim-cmp")
require("eecs.plugins.lsp.mason")
require("eecs.plugins.lsp.lspsaga")
require("eecs.plugins.lsp.lspconfig")
require("eecs.plugins.lsp.null-ls")

